name: 'Compile TeX Files'
author: 'Me, I wrote it'

inputs:
  pattern:
    description: 'The pattern for which texfiles to compile'

runs:
  using: 'composite'
  steps:
    - run: |
        echo "Pattern: ${{ inputs.pattern }}"
        find -name "${{ inputs.pattern }}" | 
          while read file
          do
            echo "$file"
            latexmk -pdf -output-directory=$(dirname "$file") "$file"
          done
