name: 'Compile TeX Files'
author: 'Tobias Udtke'

inputs:
  pull:
    description: 'Whether to pull before compiling'
    default: false
  compile-pattern:
    description: 'The pattern for which texfiles to compile'
    default: '*.tex'
  aux-directory:
    description: 'Directory in which to commit latexmk aux files'
    default: '.aux'
  commit:
    description: 'Whether to commit the resulting files'
    default: false
  commit-pattern:
    description: 'Which files to commit.'
    default: "**.pdf"
  commit-aux:
    description: 'Whether to commit aux files'
    default: true
  upload:
    description: 'Whether to upload compiled files'
    default: false
  upload-name:
    description: 'Name of the uploaded artifact'
    default: 'PDFs'
  upload-pattern:
    description: 'Which files to upload.'
    default: '**/*.pdf'

runs:
  using: 'composite'
  steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: update repository
      run: git pull --ff-only
      if: ${{ inputs.pull == true || inputs.pull == 'true' || inputs.commit == true || inputs.commit == 'true' }}
    - name: compile .tex files
      run: |
        echo ""
        echo "Pattern: ${{ inputs.compile-pattern }}"
        find -name "${{ inputs.compile-pattern }}"
        echo ""
        find -name "${{ inputs.compile-pattern }}" |
          while read file
          do
            echo "$file"
            latexmk -pdf -output-directory=$(dirname "$file") -aux-directory=${{ inputs.aux-directory }} "$file"
          done
    - name: commit pdfs
      if: ${{ inputs.commit == true || inputs.commit == 'true' }}
      run: |
        git config user.name "Auto Compile Action"
        git config user.email "compile-commit@tracker.cde-ev.de"
        git status
        git add "${{ inputs.commit-pattern }}"
        if ${{ inputs.commit-aux == true || inputs.commit-aux == 'true' }}; then
            git add -f ${{ inputs.aux-directory }}
        fi
        if ! git diff-index --quiet HEAD; then
            git status
            git commit -m "[auto] compile all PDFs" || true
            git log -n 1
            git push
        fi
    - name: upload pdfs
      if: ${{ inputs.upload == true || inputs.upload == 'true' }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.upload-name }}
        path: ${{ inputs.upload-pattern }}
    
