name: 'Compile TeX Files'
author: 'Me, I wrote it'

inputs:
  pattern:
    description: 'The pattern for which texfiles to compile'

runs:
  using: 'composite'
  steps:
    - run: echo "${{ inputs.message }}"
