name: 'Compile TeX Files'
author: 'Tobias Udtke'

inputs:
  pattern:
    description: 'The pattern for which texfiles to compile'
  aux-directory:
    description: 'Directory in which to commit latexmk aux files'
    default: '.aux'

runs:
  using: 'composite'
  steps:
    - run: |
        echo "Pattern: ${{ inputs.pattern }}"
        find -name "${{ inputs.pattern }}" | 
          while read file
          do
            echo "$file"
            latexmk -pdf -output-directory=$(dirname "$file") -aux-directory=${{ inputs.aux-directory }} "$file"
          done
